#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7  
bspc monitor eDP-1 -d 8 9 10
bspc monitor eDP-2 -d 1 2 3 4 5 6 7 8 9 10


bspc config border_width        3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Pcmanfm state=floating

feh --bg-scale /home/juan/Pictures/E5c4nVSXMAAE8gK.jpeg
/home/juan/.config/polybar/launch.sh
#feh --bg-scale /home/juan/Pictures/fondos/Pycho\ Pass/872596.jpg
#/home/juan/.config/polybar/launch.sh


#sudo /home/juan/touch.sh

picom --config /home/juan/.config/picom/picom.conf

#greenclip daemon

bspc config normal_border_color "#75A4CD"
bspc config active_border_color "#75A4CD"
bspc config focused_border_color "#00C7FF"
bspc config presel_feedback_color #000000


